export { ManufacturingHeroSection } from './ManufacturingHeroSection'
export { ManufacturingHowItWorksSection } from './ManufacturingHowItWorksSection'
export { ManufacturingCuttingPreparationSection } from './ManufacturingCuttingPreparationSection'
export { ManufacturingCapacitySection } from './ManufacturingCapacitySection'
export type { ManufacturingCapacityContent } from './ManufacturingCapacitySection'
export { ManufacturingClientsSection } from './ManufacturingClientsSection'
export { ManufacturingProductRangeSection } from './ManufacturingProductRangeSection'
export { ManufacturingCapacityDetailsSection } from './ManufacturingCapacityDetailsSection'
export { ManufacturingQualitySection } from './ManufacturingQualitySection'
export { ManufacturingSewingSection } from './ManufacturingSewingSection'
export { ManufacturingEmbroiderySection } from './ManufacturingEmbroiderySection'
export { ManufacturingProductionNetworkSection } from './ManufacturingProductionNetworkSection'
export { ManufacturingFactoriesSection } from './ManufacturingFactoriesSection'
export { ManufacturingProjectsSection } from './ManufacturingProjectsSection'
