export { DesignCTASection } from './DesignCTASection'
export { DesignExperienceSection } from './DesignExperienceSection'
export { DesignFacilitiesSection } from './DesignFacilitiesSection'
export { DesignFactoryAssuranceSection } from './DesignFactoryAssuranceSection'
export { DesignPresenceSection } from './DesignPresenceSection'
export { DesignServicesSection } from './DesignServicesSection'
export { DesignShowroomSection } from './DesignShowroomSection'
export { DesignSolutionsBannerSection } from './DesignSolutionsBannerSection'
